import React from "react";
import { View, Text, StyleSheet, ScrollView, TouchableOpacity } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useColors } from "@/hooks/useColors";
import { Feather } from "@expo/vector-icons";
import { Stack, useRouter } from "expo-router";
import Markdown from "react-native-markdown-display";

const privacyMarkdown = `
# PRIVACY POLICY
**Effective Date:** June 2026

## 1. Introduction & Scope
Welcome to PrepAssist. This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You. We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.

This comprehensive document is designed to provide complete transparency regarding the data architectures, cloud telemetry, and AI processing pipelines utilized to power your UPSC preparation journey.

## 2. Interpretation and Definitions
For the purposes of this Privacy Policy:
* **Account:** A unique account created for You to access our Service or parts of our Service.
* **Company:** Refers to PrepAssist Technologies.
* **Personal Data:** Any information that relates to an identified or identifiable individual, including your email address, name, and OAuth tokens.
* **Study Data:** Refers to the raw PDFs, images of handwritten essays, and text notes uploaded to the Cloud Vault.
* **Service:** Refers to the iOS App, Android App, Website, the AI evaluation pipelines, and the RAG infrastructure.
* **Usage Data:** Data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (e.g., page duration, API latency).

## 3. Types of Data Collected
**Personal Data**
While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to: Email address, First name and last name, and Usage Data.

**Usage Data**
Usage Data is collected automatically when using the Service. It may include information such as Your Device's Internet Protocol address (IP address), mobile device ID, operating system, the time and date of Your visit, and other diagnostic data.

**Cloud Vault & Study Data**
As an AI-driven educational platform, the core of our service relies on processing the documents you upload. When you upload syllabuses, answer sheets, or reference materials, we ingest this data into our secure Firebase storage buckets. This data is strictly partitioned and is explicitly tied to your unique cryptographic User ID.

## 4. Use of Your Personal Data
The Company may use Personal Data and Study Data for the following purposes:
* **To provide and maintain our Service:** including to monitor the usage of our Service and ensure API uptime.
* **To manage Your Account:** to manage Your registration as a user of the Service.
* **For AI Evaluation Execution:** to feed your uploaded handwritten essays into our Computer Vision models for structural grading against UPSC rubrics.
* **For Semantic Indexing (RAG):** to chunk and vectorize your uploaded PDFs so that you can instantly query them using our generative AI.
* **For Credit Ledger Synchronization:** to accurately track the computational weight of your queries and deduct the appropriate number of Credits.
* **To contact You:** To contact You by email, push notifications, or other equivalent forms of electronic communication.

## 5. Retention of Your Data
The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. Your Study Data (PDFs, Vectors, Notes) will be retained in your active Cloud Vault for as long as your account remains active. If your account is inactive for a period exceeding 24 months, we reserve the right to automatically purge your high-volume vector data to conserve server resources, following a 30-day email notice.

## 6. Third-Party AI Integrations
To provide cutting-edge cognitive capabilities, we securely transmit highly specific portions of your study data to trusted third-party APIs:
* **Google Gemini / Vertex AI:** For natural language processing and structural grading of Mains essays.
* **Pinecone Vector Database:** For mathematical embeddings to enable instant, semantic search across your uploaded documents.

**Zero-Training Guarantee:** These providers process your data entirely ephemerally to generate responses. Your private study materials are never used to train or fine-tune their base public models.

## 7. Security of Your Personal Data
We utilize Firebase Security Rules to enforce strict access control, ensuring that your Cloud Vault data can only be read by your authenticated session token. All data in transit is encrypted via TLS/SSL, and data at rest is encrypted using industry-standard AES-256 encryption.

## 8. User Rights & Data Deletion Protocol
You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You. When you execute a "Delete Account" action, our backend triggers an automated cascade that permanently purges your Firebase Auth record, your Firestore ledger, your Cloud Storage files, and all associated vectors in Pinecone.
`;

export default function PrivacyPolicyScreen() {
  const colors = useColors();
  const router = useRouter();

  return (
    <SafeAreaView style={[styles.root, { backgroundColor: colors.background }]} edges={["top"]}>
      <Stack.Screen options={{ headerShown: false }} />
      <View style={styles.header}>
        <TouchableOpacity onPress={() => router.back()} style={[styles.backBtn, { backgroundColor: colors.card }]}>
          <Feather name="chevron-left" size={24} color={colors.foreground} />
        </TouchableOpacity>
        <Text style={[styles.title, { color: colors.foreground }]}>Privacy Policy</Text>
        <View style={{ width: 44 }} />
      </View>
      <ScrollView contentContainerStyle={styles.content}>
        <Markdown 
          style={{ 
            body: { color: colors.foreground, fontSize: 15, lineHeight: 24 }, 
            heading1: { color: colors.foreground, fontFamily: "Inter_800ExtraBold", fontSize: 28, lineHeight: 36, marginTop: 10, marginBottom: 10 }, 
            heading2: { color: colors.foreground, fontFamily: "Inter_700Bold", marginTop: 16, marginBottom: 8 },
            strong: { fontFamily: "Inter_700Bold" },
            list_item: { marginBottom: 8 }
          }}
        >
          {privacyMarkdown}
        </Markdown>
        <View style={{ height: 40 }} />
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  root: { flex: 1 },
  header: { padding: 20, paddingBottom: 16, borderBottomWidth: 1, borderBottomColor: "rgba(150,150,150,0.1)", flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  title: { fontSize: 18, fontFamily: "Inter_800ExtraBold" },
  backBtn: { width: 44, height: 44, borderRadius: 22, alignItems: "center", justifyContent: "center" },
  content: { padding: 20 },
});
